// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LicenseStatus } from "./LicenseStatus";
import type { SessionUser } from "./SessionUser";

/**
 * Status aplikasi saat dibuka: license aktif? perlu setup awal? sudah ada sesi?
 */
export type AppStatus = { license: LicenseStatus, needsSetup: boolean, 
/**
 * Nama apotek dari setup awal, untuk halaman login.
 */
pharmacyName: string | null, session: SessionUser | null, };
