// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionUser } from "./SessionUser";

/**
 * Status aplikasi saat dibuka: perlu setup awal? sudah ada sesi?
 */
export type AppStatus = { needsSetup: boolean, session: SessionUser | null, };
