// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditRow } from "./AuditRow";

export type AuditPage = { rows: Array<AuditRow>, total: number, };
