// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query menu Sistem › Log. Semua filter opsional.
 */
export type AuditQuery = { 
/**
 * Cari username, nama user, atau isi detail (kode, nama, nilai sebelum/sesudah).
 */
q: string | null, 
/**
 * Nama tabel, misal `products`.
 */
entity: string | null, 
/**
 * Aksi, misal `UPDATE`. Juga cocok dengan aksi lama berawalan entitas (`PRODUCT_UPDATE`).
 */
action: string | null, userId: number | null, 
/**
 * Tanggal awal `YYYY-MM-DD` (inklusif).
 */
dateFrom: string | null, 
/**
 * Tanggal akhir `YYYY-MM-DD` (inklusif).
 */
dateTo: string | null, offset: number, limit: number, };
