// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditRow = { id: number, createdAt: string, userId: number | null, username: string | null, fullName: string | null, 
/**
 * Nama user yang mengotorisasi (misal lewat PIN), bila ada.
 */
authorizedBy: string | null, action: string, entity: string | null, entityId: number | null, 
/**
 * JSON mentah. Untuk perubahan data: `{ code, name, before, after }`.
 */
detail: string | null, reason: string | null, };
