// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User yang pernah tercatat di log, untuk pilihan filter.
 */
export type AuditUser = { id: number, username: string, fullName: string, };
