// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hasil aksi massal (banyak obat sekaligus).
 */
export type BatchResult = { 
/**
 * Jumlah data yang benar-benar berubah.
 */
done: number, 
/**
 * Alasan data yang dilewati, misal obat yang masih punya stok.
 */
skipped: Array<string>, };
