// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchSource } from "./BatchSource";

export type BatchRow = { id: number, batchNumber: string, expiryDate: string, qtyOnHandBase: number, 
/**
 * HPP per satuan terkecil (× 100). Hanya untuk user dengan VIEW_COST.
 */
unitCostX100: number | null, isLocked: boolean, lockReason: string | null, sourceType: BatchSource, createdAt: string, };
