// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

export type CategoryPage = { rows: Array<Category>, total: number, 
/**
 * Margin global yang dipakai kategori tanpa margin sendiri. `None` bila user tidak berhak melihat margin.
 */
defaultMarginBp: number | null, };
