// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category = { id: number, 
/**
 * Dibuat otomatis oleh sistem (KTG0001), tidak bisa diubah.
 */
code: string, name: string, 
/**
 * `None` bila user tidak berhak melihat margin, atau kategori tidak punya margin sendiri.
 */
marginBp: number | null, isActive: boolean, createdAt: string, 
/**
 * Username pembuat; `None` untuk data lama sebelum pembuat dicatat.
 */
createdBy: string | null, };
