// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CategoryInput = { id: number | null, 
/**
 * Kosong → dibuat otomatis (KTG0001) untuk data baru, atau tetap kode lama saat ubah.
 */
code: string | null, name: string, marginBp: number | null, isActive: boolean, };
