// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bentuk sediaan racikan.
 */
export type CompoundForm = "POWDER" | "CAPSULE" | "OINTMENT" | "LIQUID" | "OTHER";
