// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebtPanel } from "./DebtPanel";
import type { OpnamePanel } from "./OpnamePanel";
import type { RxPanel } from "./RxPanel";
import type { SalesPanel } from "./SalesPanel";
import type { ShiftPanel } from "./ShiftPanel";
import type { StockPanel } from "./StockPanel";

/**
 * Isi dashboard untuk user yang sedang login. Panel `null` = user tidak berhak melihatnya.
 */
export type Dashboard = { 
/**
 * Tanggal hari ini `YYYY-MM-DD` (jam komputer kasir).
 */
today: string, 
/**
 * Shift kasir & penjualan sendiri. Hak `SHIFT_MANAGE`.
 */
shift: ShiftPanel | null, 
/**
 * Omzet seluruh apotek. Hak `REPORT_SALES`; laba hanya dengan `VIEW_COST`.
 */
sales: SalesPanel | null, 
/**
 * Peringatan stok menipis & ED. Hak `STOCK_COUNT_INPUT`; nilai persediaan dengan `VIEW_COST`.
 */
stock: StockPanel | null, 
/**
 * Antrian resep. Hak `PRESCRIPTION_INPUT`, `PRESCRIPTION_VALIDATE`, atau `SALE_CREATE`.
 */
prescriptions: RxPanel | null, 
/**
 * Stok opname yang belum selesai. Hak `STOCK_COUNT_INPUT`.
 */
opname: OpnamePanel | null, 
/**
 * Hutang supplier. Hak `SUPPLIER_DEBT_MANAGE`.
 */
debts: DebtPanel | null, };
