// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebtSummary = { openCount: number, openAmount: number, overdueCount: number, overdueAmount: number, dueSoonCount: number, dueSoonAmount: number, };
