// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebtSummary } from "./DebtSummary";
import type { SupplierDebtRow } from "./SupplierDebtRow";

export type DebtPage = { rows: Array<SupplierDebtRow>, total: number, 
/**
 * Ringkasan semua hutang belum lunas (tanpa filter).
 */
summary: DebtSummary, today: string, };
