// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebtRow } from "./DebtRow";
import type { Tally } from "./Tally";

export type DebtPanel = { 
/**
 * Seluruh faktur kredit yang belum lunas.
 */
outstanding: Tally, 
/**
 * Sudah lewat jatuh tempo.
 */
overdue: Tally, 
/**
 * Jatuh tempo hari ini sampai 7 hari ke depan.
 */
dueSoon: Tally, 
/**
 * Faktur belum lunas, jatuh tempo terdekat dulu.
 */
upcoming: Array<DebtRow>, };
