// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebtRow = { purchaseId: number, number: string, supplierName: string, invoiceNumber: string, dueDate: string, outstanding: number, 
/**
 * Sisa hari sampai jatuh tempo; negatif = terlambat.
 */
daysLeft: number, };
