// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebtFilter } from "./DebtFilter";

export type DebtQuery = { 
/**
 * Cari nomor internal, nomor faktur, atau nama supplier.
 */
q: string | null, supplierId: number | null, filter: DebtFilter, offset: number, limit: number, };
