// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Doctor = { id: number, 
/**
 * Dibuat otomatis oleh sistem (DOK0001), tidak bisa diubah.
 */
code: string, name: string, 
/**
 * Nomor Surat Izin Praktik.
 */
sipNumber: string | null, specialty: string | null, address: string | null, phone: string | null, isActive: boolean, createdAt: string, createdBy: string | null, };
