// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DoctorInput = { id: number | null, name: string, sipNumber: string | null, specialty: string | null, address: string | null, phone: string | null, isActive: boolean, };
