// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doctor } from "./Doctor";

export type DoctorPage = { rows: Array<Doctor>, total: number, };
