// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExpiryReportQuery = { 
/**
 * Batch dengan ED sampai sekian hari ke depan ikut ditampilkan (1–730).
 */
days: number, };
