// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExpiryRow = { batchId: number, productId: number, productName: string, batchNumber: string, expiryDate: string, qtyBase: number, baseUnitName: string, 
/**
 * Sisa hari sampai ED; ≤ 0 berarti sudah ED.
 */
daysLeft: number, isLocked: boolean, };
