// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportExpiryRow } from "./ReportExpiryRow";

export type ExpiryReport = { today: string, expiredCount: number, nearCount: number, 
/**
 * Nilai HPP batch sudah ED / hampir ED. Hanya untuk `VIEW_COST`.
 */
expiredValue: number | null, nearValue: number | null, 
/**
 * Sudah ED dulu, lalu ED terdekat.
 */
rows: Array<ReportExpiryRow>, };
