// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportCategoryValue } from "./ReportCategoryValue";
import type { ReportInventoryRow } from "./ReportInventoryRow";

/**
 * Hak `VIEW_COST`.
 */
export type InventoryReport = { totalValue: number, productCount: number, batchCount: number, 
/**
 * Nilai batch yang sudah lewat ED (sudah termasuk di `total_value`).
 */
expiredValue: number, byCategory: Array<ReportCategoryValue>, 
/**
 * Obat dengan stok, nilai terbesar dulu.
 */
rows: Array<ReportInventoryRow>, };
