// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LicenseState } from "./LicenseState";

export type LicenseStatus = { state: LicenseState, 
/**
 * Alasan license tidak aktif, siap ditampilkan.
 */
message: string | null, licenseKey: string | null, 
/**
 * Waktu lokal "YYYY-MM-DD HH:MM:SS".
 */
expiresAt: string | null, activatedAt: string | null, validatedAt: string | null, 
/**
 * Sisa hari masa aktif (0 bila habis hari ini).
 */
daysLeft: number | null, maxSeats: number | null, usedSeats: number | null, machineId: string, portalUrl: string, };
