// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LowStockRow = { productId: number, code: string, name: string, stockBase: number, minStockBase: number, baseUnitName: string, };
