// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Jenis data di menu Master Data, untuk aksi bersama (aktif/nonaktif, hapus).
 */
export type MasterKind = "CATEGORY" | "RACK" | "MANUFACTURER";
