// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query daftar Master Data per halaman.
 */
export type MasterPageQuery = { 
/**
 * Cari nama atau kode (termasuk hasil scan label barcode).
 */
q: string | null, offset: number, limit: number, };
