// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovementType = "OPENING" | "PURCHASE" | "PURCHASE_VOID" | "SALE" | "SALE_VOID" | "SALE_RETURN" | "SUPPLIER_RETURN" | "ADJUSTMENT" | "DESTRUCTION";
