// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Master sederhana yang hanya berisi nama: rak dan pabrik.
 */
export type NamedItem = { id: number, 
/**
 * Dibuat otomatis oleh sistem (RAK0001 / PBR0001), tidak bisa diubah.
 */
code: string, name: string, isActive: boolean, };
