// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedItem } from "./NamedItem";

export type NamedItemPage = { rows: Array<NamedItem>, total: number, };
