// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NamedItemInput = { id: number | null, 
/**
 * Kosong → dibuat otomatis (RAK0001 / PBR0001) untuk data baru, atau tetap kode lama saat ubah.
 */
code: string | null, name: string, isActive: boolean, };
