// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tally } from "./Tally";

export type OpenShift = { id: number, openedBy: string, openedAt: string, 
/**
 * Shift ini dibuka oleh user yang sedang login.
 */
isMine: boolean, 
/**
 * Angka shift hanya untuk pemilik shift atau user dengan `REPORT_SALES`.
 */
openingCash: number | null, sales: Tally | null, 
/**
 * Uang tunai yang seharusnya ada di laci: modal + tunai masuk.
 */
expectedCash: number | null, };
