// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpnamePendingRow } from "./OpnamePendingRow";

export type OpnamePanel = { drafts: number, awaitingApproval: number, 
/**
 * Stok awal sudah dikunci.
 */
openingLocked: boolean, 
/**
 * User boleh menyetujui opname (`STOCK_COUNT_APPROVE`).
 */
canApprove: boolean, 
/**
 * Opname DRAFT & SUBMITTED, yang menunggu persetujuan lebih dulu.
 */
pending: Array<OpnamePendingRow>, };
