// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpnameStatus } from "./OpnameStatus";
import type { OpnameType } from "./OpnameType";

export type OpnameRow = { id: number, number: string, opnameType: OpnameType, scopeNote: string | null, status: OpnameStatus, itemCount: number, 
/**
 * Baris yang sudah diisi hasil hitung fisik.
 */
countedCount: number, createdAt: string, createdBy: string | null, approvedAt: string | null, approvedBy: string | null, };
