// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpnameRow } from "./OpnameRow";

export type OpnamePage = { rows: Array<OpnameRow>, total: number, 
/**
 * Stok awal sudah dikunci: opname stok awal baru tidak bisa dibuat lagi.
 */
openingLocked: boolean, };
