// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpnamePendingRow = { id: number, number: string, 
/**
 * `OPENING` / `PERIODIC`.
 */
opnameType: string, 
/**
 * `DRAFT` / `SUBMITTED`.
 */
status: string, scopeNote: string | null, createdBy: string | null, itemCount: number, createdAt: string, };
