// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpnameItemInput = { opnameId: number, 
/**
 * `None` = baris baru.
 */
id: number | null, productId: number, 
/**
 * Batch yang dihitung ulang; `None` = batch baru.
 */
batchId: number | null, 
/**
 * Wajib untuk batch baru.
 */
batchNumber: string | null, 
/**
 * `YYYY-MM-DD`, wajib untuk batch baru.
 */
expiryDate: string | null, 
/**
 * HPP per satuan terkecil (× 100), wajib untuk batch baru. `None` saat mengubah baris =
 * pertahankan HPP lama (user tanpa VIEW_COST tidak melihat nilainya).
 */
unitCostX100: number | null, physicalQtyBase: number | null, note: string | null, };
