// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpnameDetail } from "./OpnameDetail";

export type OpnameSaveResult = { opname: OpnameDetail, 
/**
 * Peringatan yang tidak menggagalkan simpan, misal ED sudah lewat.
 */
warnings: Array<string>, };
