// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpnameItem = { id: number, productId: number, productCode: string, productName: string, baseUnitName: string, 
/**
 * `None` = batch baru (stok awal atau batch yang ditemukan saat opname).
 */
batchId: number | null, batchNumber: string, expiryDate: string, 
/**
 * HPP per satuan terkecil (× 100). Hanya untuk user dengan VIEW_COST.
 */
unitCostX100: number | null, 
/**
 * HPP sudah diisi (untuk user tanpa VIEW_COST yang tidak melihat nilainya).
 */
hasCost: boolean, 
/**
 * Snapshot stok sistem saat baris ditambahkan.
 */
systemQtyBase: number, physicalQtyBase: number | null, note: string | null, };
