// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpnameStatus } from "./OpnameStatus";

export type OpnamePageQuery = { 
/**
 * Cari nomor atau keterangan.
 */
q: string | null, status: OpnameStatus | null, offset: number, limit: number, };
