// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpnameItem } from "./OpnameItem";
import type { OpnameRow } from "./OpnameRow";

export type OpnameDetail = { header: OpnameRow, items: Array<OpnameItem>, 
/**
 * Nilai selisih (Σ selisih × HPP, rupiah). Hanya untuk user dengan VIEW_COST.
 */
differenceValue: number | null, };
