// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpnameType } from "./OpnameType";

export type OpnameCreateInput = { opnameType: OpnameType, 
/**
 * Cakupan, misal "Rak Obat Bebas A".
 */
scopeNote: string | null, };
