// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";

export type PatientInput = { id: number | null, name: string, gender: Gender | null, birthDate: string | null, address: string | null, phone: string | null, isActive: boolean, };
