// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Patient } from "./Patient";

export type PatientPage = { rows: Array<Patient>, total: number, };
