// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";

export type Patient = { id: number, 
/**
 * Dibuat otomatis oleh sistem (PSN0001), tidak bisa diubah.
 */
code: string, name: string, gender: Gender | null, 
/**
 * `YYYY-MM-DD`.
 */
birthDate: string | null, address: string | null, phone: string | null, isActive: boolean, createdAt: string, createdBy: string | null, };
