// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metode bayar. Non-tunai dicatat manual (tanpa integrasi bank).
 */
export type PaymentMethod = "CASH" | "QRIS" | "DEBIT";
