// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentMethod } from "./PaymentMethod";

export type PaymentInput = { method: PaymentMethod, 
/**
 * Bagian tagihan yang dibayar dengan metode ini.
 */
amount: number, 
/**
 * Uang diterima (tunai saja); kembalian = tendered − amount.
 */
tendered: number | null, 
/**
 * Kode approval EDC / QRIS.
 */
reference: string | null, };
