// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentMethod } from "./PaymentMethod";

export type PaymentDetail = { method: PaymentMethod, amount: number, tendered: number | null, changeAmount: number | null, reference: string | null, };
