// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hak akses. Keputusan akhir selalu diperiksa di command Rust.
 */
export type Permission = "SALE_CREATE" | "SHIFT_MANAGE" | "RECEIPT_REPRINT" | "SELL_HARD_DRUG" | "PRESCRIPTION_INPUT" | "PRESCRIPTION_VALIDATE" | "PRODUCT_MANAGE" | "PRICE_MANAGE" | "PURCHASE_RECEIVE" | "SUPPLIER_DEBT_MANAGE" | "STOCK_COUNT_INPUT" | "STOCK_COUNT_APPROVE" | "STOCK_DESTROY" | "TRANSACTION_VOID" | "DISCOUNT_OVERRIDE" | "VIEW_COST" | "REPORT_SALES" | "REPORT_SALES_OWN_SHIFT" | "REPORT_SIPNAP" | "USER_MANAGE" | "SETTINGS_MANAGE" | "BACKUP_MANAGE" | "AUDIT_VIEW";
