// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrugClass } from "./DrugClass";
import type { PosUnit } from "./PosUnit";

export type PosProduct = { productId: number, code: string, name: string, genericName: string | null, drugClass: DrugClass, isOwa: boolean, baseUnitName: string, 
/**
 * Stok yang bisa dijual (belum ED, tidak terkunci), satuan terkecil.
 */
sellableBase: number, units: Array<PosUnit>, 
/**
 * Satuan yang cocok dengan barcode yang di-scan.
 */
matchedUnitId: number | null, };
