// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PosPrescription = { id: number, number: string, prescriptionNumber: string, prescriptionDate: string, patientName: string, doctorName: string, screenedAt: string | null, itemCount: number, };
