// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShiftSummary } from "./ShiftSummary";

/**
 * Keadaan layar kasir: shift terbuka dan aturan yang dipakai saat menghitung total.
 */
export type PosState = { shift: ShiftSummary | null, 
/**
 * Diskon per baris maksimal (basis point dari harga baris) tanpa otorisasi PIN.
 */
maxDiscountBp: number, 
/**
 * Total nota dibulatkan ke bawah ke kelipatan ini (rupiah); 0 = tanpa pembulatan.
 */
totalRounding: number, 
/**
 * Resep yang sudah divalidasi apoteker dan menunggu dibayar.
 */
prescriptionsReady: number, };
