// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PosTier } from "./PosTier";

export type PosUnit = { productUnitId: number, unitName: string, conversion: number, sellPrice: number, isDefault: boolean, 
/**
 * Harga grosir, `minQty` naik.
 */
tiers: Array<PosTier>, };
