// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DRAFT (menunggu skrining) → SCREENED (siap dibayar) → PAID (dibayar di kasir).
 * Resep yang diubah setelah divalidasi kembali ke DRAFT. Batal = CANCELLED.
 */
export type PrescriptionStatus = "DRAFT" | "SCREENED" | "PAID" | "CANCELLED";
