// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuoteLine } from "./QuoteLine";

/**
 * Hitungan harga final resep saat akan dibayar (harga terbaru, sudah harga tier).
 */
export type PrescriptionQuote = { id: number, number: string, prescriptionNumber: string, patientName: string, doctorName: string, lines: Array<QuoteLine>, subtotal: number, rounding: number, grandTotal: number, 
/**
 * Stok kurang, obat nonaktif, dll. Resep dengan peringatan tidak bisa dibayar.
 */
problems: Array<string>, };
