// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrescriptionStatus } from "./PrescriptionStatus";

export type PrescriptionQuery = { 
/**
 * Cari nomor internal, nomor resep dokter, nama pasien, atau nama dokter.
 */
q: string | null, status: PrescriptionStatus | null, 
/**
 * Tanggal resep `YYYY-MM-DD`, inklusif.
 */
dateFrom: string | null, dateTo: string | null, offset: number, limit: number, };
