// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrescriptionItemDetail } from "./PrescriptionItemDetail";
import type { PrescriptionStatus } from "./PrescriptionStatus";

export type PrescriptionDetail = { id: number, number: string, prescriptionNumber: string, prescriptionDate: string, doctorId: number, doctorName: string, doctorSipNumber: string | null, customerId: number | null, patientName: string, patientAge: string | null, patientAddress: string | null, note: string | null, status: PrescriptionStatus, screenedBy: string | null, screenedAt: string | null, screeningNote: string | null, createdAt: string, createdBy: string | null, cancelledAt: string | null, cancelledBy: string | null, cancelReason: string | null, items: Array<PrescriptionItemDetail>, 
/**
 * Jumlah semua baris utama (perkiraan; harga final dihitung saat dibayar).
 */
total: number, 
/**
 * Peringatan yang tidak menghalangi, misal stok kurang.
 */
warnings: Array<string>, };
