// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrescriptionRow } from "./PrescriptionRow";

export type PrescriptionPage = { rows: Array<PrescriptionRow>, total: number, 
/**
 * Jumlah resep menunggu skrining (semua tanggal), untuk penanda di tab.
 */
draftCount: number, 
/**
 * Jumlah resep siap dibayar (semua tanggal).
 */
screenedCount: number, };
