// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrescriptionStatus } from "./PrescriptionStatus";

export type PrescriptionRow = { id: number, number: string, prescriptionNumber: string, prescriptionDate: string, doctorName: string, patientName: string, patientAge: string | null, 
/**
 * Jumlah baris utama (obat, racikan, jasa).
 */
itemCount: number, total: number, 
/**
 * Berisi narkotika / psikotropika.
 */
hasControlled: boolean, status: PrescriptionStatus, createdAt: string, createdBy: string | null, screenedBy: string | null, };
