// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrescriptionItemInput } from "./PrescriptionItemInput";

export type PrescriptionInput = { id: number | null, 
/**
 * Nomor resep yang ditulis dokter.
 */
prescriptionNumber: string, 
/**
 * `YYYY-MM-DD`.
 */
prescriptionDate: string, doctorId: number, 
/**
 * Pasien terdaftar (opsional). Nama/umur/alamat tetap disimpan sebagai snapshot.
 */
customerId: number | null, patientName: string, patientAge: string | null, patientAddress: string | null, note: string | null, items: Array<PrescriptionItemInput>, };
