// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompoundForm } from "./CompoundForm";
import type { DrugClass } from "./DrugClass";
import type { ItemKind } from "./ItemKind";

export type PrescriptionItemDetail = { id: number, lineNo: number, kind: ItemKind, productId: number | null, productUnitId: number | null, productCode: string | null, unitName: string | null, drugClass: DrugClass | null, description: string, compoundForm: CompoundForm | null, qty: number, conversion: number, qtyBase: number, unitPrice: number, 
/**
 * Tier harga grosir yang dipakai (jumlah minimalnya); `None` = harga eceran.
 */
tierMinQty: number | null, lineTotal: number, usageInstruction: string | null, 
/**
 * Stok yang bisa dijual (belum ED, tidak terkunci), dalam satuan terkecil. Hanya untuk obat.
 */
stockBase: number | null, 
/**
 * Komponen racikan (hanya untuk `COMPOUND`).
 */
components: Array<PrescriptionItemDetail>, };
