// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompoundComponentInput } from "./CompoundComponentInput";
import type { CompoundForm } from "./CompoundForm";
import type { ItemKind } from "./ItemKind";

export type PrescriptionItemInput = { kind: ItemKind, 
/**
 * Wajib untuk `PRODUCT`.
 */
productUnitId: number | null, 
/**
 * Jumlah dalam satuan jual (obat), jumlah bungkus/kapsul/pot (racikan), atau 1 (jasa).
 */
qty: number, 
/**
 * Wajib untuk racikan dan jasa; untuk obat diisi otomatis nama obat.
 */
description: string | null, 
/**
 * Wajib untuk racikan.
 */
compoundForm: CompoundForm | null, 
/**
 * Tarif per jumlah, hanya untuk jasa. Harga obat selalu dihitung sistem.
 */
unitPrice: number | null, 
/**
 * Aturan pakai (signa) untuk etiket, misal "3 x sehari 1 tablet sesudah makan".
 */
usageInstruction: string | null, 
/**
 * Komponen racikan: jumlah total untuk seluruh racikan.
 */
components: Array<CompoundComponentInput>, };
