// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceMode } from "./PriceMode";

export type PriceTierDetail = { id: number, minQty: number, priceMode: PriceMode, 
/**
 * Hanya untuk user yang boleh melihat/mengatur harga.
 */
marginBp: number | null, price: number, };
