// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceMode } from "./PriceMode";

export type PriceTierInput = { 
/**
 * Tier dikenali lewat jumlah minimal per satuan.
 */
minQty: number, priceMode: PriceMode, 
/**
 * Wajib bila `AUTO`.
 */
marginBp: number | null, 
/**
 * Dipakai bila `MANUAL`.
 */
price: number, };
