// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitPriceInput } from "./UnitPriceInput";

export type ProductPricesInput = { productId: number, 
/**
 * Margin milik obat; `None` = ikut kategori/default.
 */
marginBp: number | null, 
/**
 * HPP acuan per satuan terkecil (× 100). Hanya diterapkan untuk user dengan VIEW_COST;
 * nantinya diperbarui otomatis oleh penerimaan barang.
 */
lastCostX100: number | null, units: Array<UnitPriceInput>, };
