// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrugClass } from "./DrugClass";
import type { ProductUnitDetail } from "./ProductUnitDetail";

export type ProductDetail = { id: number, code: string, name: string, genericName: string | null, manufacturer: string | null, categoryId: number | null, drugClass: DrugClass, isOwa: boolean, baseUnitId: number, minStockBase: number, rackLocation: string | null, isActive: boolean, 
/**
 * Sudah punya batch → satuan dasar & konversi satuan lama tidak bisa diubah.
 */
hasStock: boolean, 
/**
 * Margin milik obat ini (bukan warisan). Hanya untuk user yang boleh melihat/mengatur harga.
 */
marginBp: number | null, 
/**
 * Margin yang berlaku (obat → kategori → default). Hanya untuk user yang boleh melihat/mengatur harga.
 */
effectiveMarginBp: number | null, 
/**
 * HPP acuan per satuan terkecil (× 100). Hanya untuk user dengan VIEW_COST.
 */
lastCostX100: number | null, units: Array<ProductUnitDetail>, };
