// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductUnitInput = { id: number | null, unitId: number, conversion: number, isDefaultSale: boolean, barcodes: Array<string>, };
