// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrugClass } from "./DrugClass";

export type ProductListRow = { id: number, code: string, name: string, genericName: string | null, categoryName: string | null, drugClass: DrugClass, isOwa: boolean, baseUnitName: string, saleUnitName: string | null, salePrice: number | null, 
/**
 * Total stok semua batch, dalam satuan terkecil.
 */
stockBase: number, minStockBase: number, rackLocation: string | null, isActive: boolean, };
