// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchRow } from "./BatchRow";

export type ProductBatches = { productId: number, code: string, name: string, baseUnitName: string, 
/**
 * Termasuk batch yang stoknya sudah habis bila diminta.
 */
batches: Array<BatchRow>, };
