// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceMode } from "./PriceMode";
import type { PriceTierDetail } from "./PriceTierDetail";

export type ProductUnitDetail = { id: number, unitId: number, unitName: string, conversion: number, sellPrice: number, priceMode: PriceMode, isDefaultSale: boolean, isActive: boolean, barcodes: Array<string>, tiers: Array<PriceTierDetail>, };
