// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrugClass } from "./DrugClass";
import type { ProductUnitInput } from "./ProductUnitInput";

export type ProductInput = { id: number | null, 
/**
 * Kosong → dibuat otomatis (OBT00001).
 */
code: string | null, name: string, genericName: string | null, manufacturerId: number | null, categoryId: number | null, drugClass: DrugClass, isOwa: boolean, baseUnitId: number, minStockBase: number, rackId: number | null, 
/**
 * Semua satuan aktif. Satuan lama yang tidak dikirim akan dinonaktifkan.
 */
units: Array<ProductUnitInput>, };
