// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductDetail } from "./ProductDetail";

export type ProductSaveResult = { product: ProductDetail, 
/**
 * Peringatan yang tidak menggagalkan simpan, misal harga di bawah HPP.
 */
warnings: Array<string>, };
