// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrugClass } from "./DrugClass";

export type ProductListQuery = { 
/**
 * Cari nama, nama generik, kode, atau barcode persis.
 */
q: string | null, categoryId: number | null, drugClass: DrugClass | null, includeInactive: boolean, offset: number, limit: number, };
