// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportProductRow } from "./ReportProductRow";
import type { ReportSlowRow } from "./ReportSlowRow";

export type ProductReport = { from: string, to: string, 
/**
 * Obat terjual, nilai terbesar dulu.
 */
top: Array<ReportProductRow>, 
/**
 * Obat aktif yang masih ada stok tetapi tidak terjual dalam rentang.
 */
slow: Array<ReportSlowRow>, };
