// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurchaseItemDetail } from "./PurchaseItemDetail";
import type { PurchasePaymentType } from "./PurchasePaymentType";
import type { PurchaseStatus } from "./PurchaseStatus";
import type { SupplierPaymentRow } from "./SupplierPaymentRow";
import type { TaxMode } from "./TaxMode";

export type PurchaseDetail = { id: number, number: string, supplierId: number, supplierName: string, invoiceNumber: string, invoiceDate: string, receivedDate: string, dueDate: string | null, paymentType: PurchasePaymentType, taxMode: TaxMode, taxRateBp: number, status: PurchaseStatus, note: string | null, 
/**
 * Σ qty × harga (sebelum diskon).
 */
subtotal: number, extraDiscount: number, 
/**
 * Diskon baris + diskon faktur.
 */
discountTotal: number, taxTotal: number, grandTotal: number, 
/**
 * PPN masuk HPP (non-PKP). Draft: pengaturan saat ini; setelah posting: snapshot.
 */
taxInCost: boolean, items: Array<PurchaseItemDetail>, createdAt: string, createdBy: string | null, postedAt: string | null, postedBy: string | null, voidedAt: string | null, voidedBy: string | null, voidReason: string | null, 
/**
 * Sisa hutang (kredit & diposting). Hanya untuk `SUPPLIER_DEBT_MANAGE`.
 */
outstanding: number | null, 
/**
 * Riwayat pembayaran (termasuk yang dibatalkan). Hanya untuk `SUPPLIER_DEBT_MANAGE`.
 */
payments: Array<SupplierPaymentRow> | null, };
