// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrugClass } from "./DrugClass";
import type { PurchaseUnit } from "./PurchaseUnit";

export type PurchaseItemDetail = { id: number, lineNo: number, productId: number, productCode: string, productName: string, drugClass: DrugClass, productUnitId: number, unitName: string, baseUnitName: string, 
/**
 * Isi satuan beli (snapshot).
 */
conversion: number, qty: number, bonusQty: number, unitPrice: number, discount1Bp: number, discount2Bp: number, 
/**
 * Setelah diskon baris, sebelum diskon faktur & PPN.
 */
lineTotal: number, batchNumber: string, expiryDate: string, 
/**
 * Stok yang masuk (qty + bonus) dalam satuan terkecil.
 */
qtyBase: number, 
/**
 * HPP per satuan terkecil (× 100). Draft: perkiraan dengan pengaturan pajak saat ini.
 * Hanya untuk `VIEW_COST`.
 */
unitCostX100: number | null, 
/**
 * HPP acuan obat sebelum faktur ini (pembanding harga naik). Hanya untuk `VIEW_COST`.
 */
lastCostX100: number | null, 
/**
 * Batch yang dibuat saat posting.
 */
batchId: number | null, 
/**
 * Satuan beli yang bisa dipilih (hanya untuk draft, agar baris bisa diubah).
 */
units: Array<PurchaseUnit>, };
