// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportInvoiceRow } from "./ReportInvoiceRow";
import type { ReportSupplierRow } from "./ReportSupplierRow";

/**
 * Faktur `POSTED` menurut tanggal terima. Hak `PURCHASE_RECEIVE`.
 */
export type PurchaseReport = { from: string, to: string, count: number, subtotal: number, discount: number, tax: number, total: number, cashTotal: number, creditTotal: number, bySupplier: Array<ReportSupplierRow>, invoices: Array<ReportInvoiceRow>, 
/**
 * Sisa hutang faktur ini hanya dikirim untuk `SUPPLIER_DEBT_MANAGE`.
 */
showsDebt: boolean, };
