// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurchasePostInput = { id: number, 
/**
 * Perbarui HPP acuan obat dan hitung ulang harga jual `AUTO` dari margin.
 */
updatePrices: boolean, };
