// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nilai awal form faktur.
 */
export type PurchaseDefaults = { 
/**
 * Tarif PPN default (basis point).
 */
taxRateBp: number, 
/**
 * Apotek PKP: PPN tidak masuk HPP.
 */
isPkp: boolean, 
/**
 * Batas "ED dekat" untuk peringatan (hari).
 */
nearExpiryDays: number, today: string, };
