// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DRAFT (boleh setengah jadi) → POSTED (stok bertambah) → VOID (batal).
 */
export type PurchaseStatus = "DRAFT" | "POSTED" | "VOID";
