// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurchaseItemInput } from "./PurchaseItemInput";
import type { PurchasePaymentType } from "./PurchasePaymentType";
import type { TaxMode } from "./TaxMode";

export type PurchaseInput = { 
/**
 * `None` = faktur baru.
 */
id: number | null, supplierId: number, invoiceNumber: string, invoiceDate: string, receivedDate: string, 
/**
 * Wajib untuk kredit.
 */
dueDate: string | null, paymentType: PurchasePaymentType, taxMode: TaxMode, taxRateBp: number, 
/**
 * Diskon faktur tingkat header (rupiah).
 */
extraDiscount: number, note: string | null, items: Array<PurchaseItemInput>, };
