// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurchaseDetail } from "./PurchaseDetail";

export type PurchaseSaveResult = { purchase: PurchaseDetail, 
/**
 * Peringatan yang tidak menggagalkan simpan, misal ED dekat atau harga beli naik.
 */
warnings: Array<string>, };
