// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrugClass } from "./DrugClass";
import type { PurchaseUnit } from "./PurchaseUnit";

/**
 * Obat untuk baris faktur: satuan beli yang bisa dipilih.
 */
export type PurchaseProduct = { productId: number, code: string, name: string, genericName: string | null, drugClass: DrugClass, baseUnitName: string, 
/**
 * Urut isi terbesar dulu (box, strip, tablet).
 */
units: Array<PurchaseUnit>, 
/**
 * Satuan yang cocok dengan barcode yang di-scan.
 */
matchedUnitId: number | null, 
/**
 * HPP acuan per satuan terkecil (× 100). Hanya untuk `VIEW_COST`.
 */
lastCostX100: number | null, };
