// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurchaseStatus } from "./PurchaseStatus";

export type PurchaseQuery = { 
/**
 * Cari nomor internal, nomor faktur, atau nama supplier.
 */
q: string | null, status: PurchaseStatus | null, supplierId: number | null, 
/**
 * Tanggal terima `YYYY-MM-DD`, inklusif.
 */
dateFrom: string | null, dateTo: string | null, offset: number, limit: number, };
