// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurchasePaymentType } from "./PurchasePaymentType";
import type { PurchaseStatus } from "./PurchaseStatus";

export type PurchaseRow = { id: number, 
/**
 * Nomor internal `PB-2609-0001`.
 */
number: string, supplierId: number, supplierName: string, invoiceNumber: string, invoiceDate: string, receivedDate: string, dueDate: string | null, paymentType: PurchasePaymentType, status: PurchaseStatus, itemCount: number, grandTotal: number, createdAt: string, createdBy: string | null, postedAt: string | null, 
/**
 * Sisa hutang faktur kredit yang sudah diposting. Hanya untuk `SUPPLIER_DEBT_MANAGE`.
 */
outstanding: number | null, };
