// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurchaseRow } from "./PurchaseRow";

export type PurchasePage = { rows: Array<PurchaseRow>, total: number, };
