// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurchaseItemInput = { 
/**
 * Satuan beli (box/strip/...); obat ikut dari satuan ini.
 */
productUnitId: number, 
/**
 * Jumlah dalam satuan beli.
 */
qty: number, 
/**
 * Bonus dalam satuan beli (tanpa harga).
 */
bonusQty: number, 
/**
 * Harga beli per satuan beli sesuai faktur.
 */
unitPrice: number, discount1Bp: number, discount2Bp: number, batchNumber: string, 
/**
 * `YYYY-MM-DD`.
 */
expiryDate: string, };
