// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuoteLine = { kind: string, description: string, unitName: string | null, qty: number, unitPrice: number, lineTotal: number, components: Array<QuoteLine>, };
