// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rentang tanggal laporan, keduanya `YYYY-MM-DD` dan inklusif.
 */
export type ReportRange = { from: string, to: string, };
