// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportProductRow = { productId: number, code: string, name: string, qtyBase: number, baseUnitName: string, 
/**
 * Jumlah nota yang memuat obat ini.
 */
saleCount: number, amount: number, 
/**
 * HPP & laba kotor baris (tanpa PPN). Hanya untuk `VIEW_COST`.
 */
cost: number | null, grossProfit: number | null, };
