// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportDay = { date: string, count: number, amount: number, 
/**
 * Hanya untuk `VIEW_COST`.
 */
grossProfit: number | null, };
