// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportExpiryRow = { batchId: number, productId: number, code: string, productName: string, batchNumber: string, expiryDate: string, qtyBase: number, baseUnitName: string, 
/**
 * ≤ 0 berarti sudah ED.
 */
daysLeft: number, isLocked: boolean, value: number | null, };
