// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shift yang dibuka dalam rentang. Penjualan = nota yang terlihat oleh user (lihat `own_only`).
 */
export type ReportShift = { id: number, openedBy: string, openedAt: string, closedAt: string | null, 
/**
 * `OPEN` / `CLOSED`.
 */
status: string, count: number, amount: number, 
/**
 * Angka kas hanya untuk pemilik shift atau `REPORT_SALES`.
 */
openingCash: number | null, expectedCash: number | null, countedCash: number | null, difference: number | null, };
