// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportInventoryRow = { productId: number, code: string, name: string, category: string | null, stockBase: number, baseUnitName: string, batchCount: number, value: number, };
