// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportInvoiceRow = { purchaseId: number, number: string, supplierName: string, invoiceNumber: string, receivedDate: string, 
/**
 * `CASH` / `CREDIT`.
 */
paymentType: string, dueDate: string | null, total: number, 
/**
 * Sisa hutang (faktur kredit). Hanya untuk `SUPPLIER_DEBT_MANAGE`.
 */
outstanding: number | null, };
