// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportSlowRow = { productId: number, code: string, name: string, stockBase: number, baseUnitName: string, 
/**
 * Tanggal terakhir terjual (kapan pun), `null` bila belum pernah.
 */
lastSoldAt: string | null, 
/**
 * Nilai stok (Σ qty × HPP). Hanya untuk `VIEW_COST`.
 */
value: number | null, };
