// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Peran pengguna. Lihat docs/FLOW.md bagian 1.
 */
export type Role = "OWNER" | "PHARMACIST" | "TECHNICIAN" | "CASHIER";
