// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RxQueueRow } from "./RxQueueRow";

export type RxPanel = { 
/**
 * Resep DRAFT, menunggu skrining apoteker.
 */
awaitingScreening: number, 
/**
 * Resep sudah divalidasi, menunggu dibayar di kasir.
 */
readyToPay: number, 
/**
 * Antrian yang relevan untuk user: `DRAFT` untuk yang input/validasi resep,
 * `SCREENED` untuk kasir.
 */
queueStatus: string, queue: Array<RxQueueRow>, };
