// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RxQueueRow = { id: number, number: string, prescriptionDate: string, patientName: string, doctorName: string, 
/**
 * Jumlah item (obat, racikan, jasa) tanpa komponen racikan.
 */
itemCount: number, createdAt: string, };
