// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaleBatch } from "./SaleBatch";

export type SaleItemDetail = { id: number, lineNo: number, 
/**
 * `PRODUCT` / `COMPOUND` / `SERVICE`.
 */
kind: string, 
/**
 * Komponen racikan menunjuk ke baris `COMPOUND`.
 */
parentItemId: number | null, description: string, unitName: string | null, qty: number, unitPrice: number, tierMinQty: number | null, discountAmount: number, lineTotal: number, usageInstruction: string | null, 
/**
 * Batch yang terpakai (FEFO), untuk penelusuran.
 */
batches: Array<SaleBatch>, };
