// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaleRow } from "./SaleRow";

export type SalePage = { rows: Array<SaleRow>, total: number, };
