// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyTotal } from "./DailyTotal";
import type { MethodTotal } from "./MethodTotal";
import type { Tally } from "./Tally";
import type { TopProduct } from "./TopProduct";

export type SalesPanel = { today: Tally, yesterday: Tally, 
/**
 * Bulan berjalan sampai hari ini.
 */
month: Tally, 
/**
 * Nota yang dibatalkan hari ini.
 */
voidToday: Tally, 
/**
 * Penjualan resep hari ini (sudah termasuk di `today`).
 */
prescriptionToday: Tally, byMethodToday: Array<MethodTotal>, 
/**
 * 7 hari terakhir termasuk hari ini, urut tanggal; hari tanpa penjualan bernilai 0.
 */
daily: Array<DailyTotal>, 
/**
 * Obat terlaris bulan ini menurut nilai penjualan.
 */
topProducts: Array<TopProduct>, 
/**
 * Laba kotor (penjualan tanpa PPN − HPP batch). Hanya untuk `VIEW_COST`.
 */
grossProfitToday: number | null, grossProfitMonth: number | null, };
