// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaleItemInput = { productUnitId: number, qty: number, 
/**
 * Diskon rupiah untuk seluruh baris.
 */
discountAmount: number, };
