// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentInput } from "./PaymentInput";
import type { SaleItemInput } from "./SaleItemInput";

export type SaleInput = { 
/**
 * Kunci idempotensi dari layar kasir (UUID), tetap sama saat kirim ulang checkout yang sama.
 */
clientRef: string, 
/**
 * Diisi untuk membayar resep berstatus `SCREENED`; `items` diabaikan (diambil dari resep).
 */
prescriptionId: number | null, items: Array<SaleItemInput>, payments: Array<PaymentInput>, 
/**
 * Total yang dilihat kasir. Ditolak bila berbeda dengan hitungan sistem (misal harga baru diubah).
 */
expectedTotal: number, 
/**
 * PIN apoteker untuk obat keras, bila kasir sendiri tidak berhak.
 */
hardDrugPin: string | null, 
/**
 * PIN untuk diskon di atas batas, bila kasir sendiri tidak berhak.
 */
discountPin: string | null, };
