// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SalesReportSummary = { 
/**
 * Nota selesai (tidak batal).
 */
count: number, 
/**
 * Σ subtotal sebelum diskon nota.
 */
subtotal: number, discount: number, tax: number, rounding: number, 
/**
 * Omzet = Σ grand total.
 */
net: number, prescriptionCount: number, prescriptionAmount: number, 
/**
 * Nota batal, menurut tanggal pembatalan.
 */
voidCount: number, voidAmount: number, 
/**
 * HPP batch terpakai & laba kotor (penjualan tanpa PPN − HPP). Hanya untuk `VIEW_COST`.
 */
cost: number | null, grossProfit: number | null, };
