// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaleVoidInput = { saleId: number, reason: string, 
/**
 * PIN Pemilik/Apoteker, bila user sendiri tidak berhak membatalkan.
 */
pin: string | null, };
