// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaleQuery = { 
/**
 * Kosong = shift yang sedang terbuka.
 */
shiftId: number | null, 
/**
 * Cari nomor nota.
 */
q: string | null, offset: number, limit: number, };
