// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportCashier } from "./ReportCashier";
import type { ReportDay } from "./ReportDay";
import type { ReportMethod } from "./ReportMethod";
import type { ReportShift } from "./ReportShift";
import type { SalesReportSummary } from "./SalesReportSummary";

/**
 * Laporan penjualan per periode. Tanpa `REPORT_SALES` hanya berisi nota user sendiri.
 */
export type SalesReport = { from: string, to: string, 
/**
 * `true` = hanya penjualan user yang sedang login (hak `REPORT_SALES_OWN_SHIFT`).
 */
ownOnly: boolean, summary: SalesReportSummary, 
/**
 * Setiap tanggal dalam rentang, termasuk yang tanpa penjualan.
 */
daily: Array<ReportDay>, byMethod: Array<ReportMethod>, byCashier: Array<ReportCashier>, shifts: Array<ReportShift>, };
