// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentDetail } from "./PaymentDetail";
import type { SaleItemDetail } from "./SaleItemDetail";

export type SaleDetail = { id: number, number: string, shiftId: number, cashierName: string, soldAt: string, 
/**
 * `OTC` / `PRESCRIPTION`.
 */
saleType: string, prescriptionId: number | null, prescriptionNumber: string | null, patientName: string | null, subtotal: number, discountTotal: number, rounding: number, grandTotal: number, 
/**
 * `COMPLETED` / `VOID`.
 */
status: string, voidedAt: string | null, voidedBy: string | null, voidReason: string | null, items: Array<SaleItemDetail>, payments: Array<PaymentDetail>, changeAmount: number, 
/**
 * Nota ini sudah tersimpan sebelumnya dengan `clientRef` yang sama (kiriman ulang).
 */
replayed: boolean, };
