// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaleRow = { id: number, number: string, soldAt: string, cashierName: string, saleType: string, itemCount: number, grandTotal: number, status: string, 
/**
 * Metode bayar, misal "CASH+QRIS".
 */
methods: string, };
