// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";
import type { Role } from "./Role";

/**
 * User yang sedang login beserta hak efektifnya.
 */
export type SessionUser = { id: number, username: string, fullName: string, roles: Array<Role>, permissions: Array<Permission>, };
