// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Setup awal: membuat akun pemilik pertama.
 */
export type SetupInput = { pharmacyName: string, fullName: string, username: string, password: string, pin: string, 
/**
 * Pemilik juga apoteker → diberi peran PHARMACIST.
 */
alsoPharmacist: boolean, 
/**
 * Nomor SIPA, wajib bila `also_pharmacist`.
 */
licenseNumber: string | null, };
