// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MethodAmount } from "./MethodAmount";

export type ShiftFigures = { openingCash: number, saleCount: number, salesTotal: number, voidCount: number, 
/**
 * Bagian tunai dari nota yang tidak batal.
 */
cashIn: number, 
/**
 * Modal + tunai masuk = uang yang seharusnya ada di laci.
 */
expectedCash: number, byMethod: Array<MethodAmount>, 
/**
 * Terisi setelah shift ditutup.
 */
countedCash: number | null, difference: number | null, };
