// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenShift } from "./OpenShift";
import type { Tally } from "./Tally";

export type ShiftPanel = { 
/**
 * Shift yang sedang terbuka (hanya satu per aplikasi), bila ada.
 */
open: OpenShift | null, 
/**
 * Penjualan user ini hari ini (semua shift).
 */
mySalesToday: Tally, };
