// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShiftCloseInput = { 
/**
 * Shift yang ditampilkan di layar; ditolak bila ternyata sudah berganti.
 */
shiftId: number, countedCash: number, note: string | null, };
