// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShiftFigures } from "./ShiftFigures";

export type ShiftSummary = { id: number, openedById: number, openedBy: string, openedAt: string, isMine: boolean, 
/**
 * `OPEN` / `CLOSED`.
 */
status: string, closedAt: string | null, 
/**
 * Angka shift hanya untuk pemilik shift atau user dengan `REPORT_SALES`.
 */
figures: ShiftFigures | null, };
