// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SipnapRow } from "./SipnapRow";

/**
 * Mutasi narkotika & psikotropika sebulan dari kartu stok. Hak `REPORT_SIPNAP`.
 */
export type SipnapReport = { year: number, month: number, rows: Array<SipnapRow>, };
