// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semua jumlah dalam satuan dasar. `closing = opening + received − sold − destroyed + adjusted`.
 */
export type SipnapRow = { productId: number, code: string, name: string, 
/**
 * `NARCOTIC` / `PSYCHOTROPIC`.
 */
drugClass: string, baseUnitName: string, opening: number, 
/**
 * Stok awal, pembelian (dikurangi batal beli).
 */
received: number, 
/**
 * Penjualan bersih (dikurangi batal jual dan retur penjualan).
 */
sold: number, 
/**
 * Pemusnahan dan retur ke supplier.
 */
destroyed: number, 
/**
 * Penyesuaian opname (±).
 */
adjusted: number, closing: number, };
