// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockRow } from "./StockRow";

export type StockPage = { rows: Array<StockRow>, total: number, 
/**
 * Tanggal hari ini menurut aplikasi (`YYYY-MM-DD`), dasar status ED di tampilan.
 */
today: string, };
