// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovementType } from "./MovementType";

export type StockCardRow = { id: number, createdAt: string, movementType: MovementType, batchId: number, batchNumber: string, expiryDate: string, 
/**
 * Bertanda: + masuk, − keluar (satuan terkecil).
 */
qtyChangeBase: number, 
/**
 * Saldo setelah kejadian ini.
 */
balanceBase: number, refType: string, refId: number, 
/**
 * Nomor dokumen asal (misal nomor opname), bila dikenali.
 */
refNumber: string | null, username: string | null, note: string | null, };
