// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpiryRow } from "./ExpiryRow";
import type { LowStockRow } from "./LowStockRow";

export type StockPanel = { 
/**
 * Obat aktif dengan stok di bawah stok minimal (termasuk yang kosong).
 */
lowCount: number, 
/**
 * Obat aktif dengan stok nol.
 */
emptyCount: number, 
/**
 * Batch ber-stok dengan ED ≤ 3 bulan dan belum lewat.
 */
nearExpiryCount: number, 
/**
 * Batch ber-stok yang sudah lewat ED (terkunci otomatis, tidak bisa dijual).
 */
expiredCount: number, 
/**
 * Batch sudah ED dulu, lalu yang hampir ED; urut ED terdekat.
 */
expiring: Array<ExpiryRow>, 
/**
 * Obat paling kritis (stok / minimal terkecil).
 */
lowStock: Array<LowStockRow>, 
/**
 * Nilai persediaan (Σ qty × HPP, rupiah). Hanya untuk `VIEW_COST`.
 */
inventoryValue: number | null, };
