// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockCardRow } from "./StockCardRow";

export type StockCardPage = { rows: Array<StockCardRow>, total: number, 
/**
 * Saldo sebelum `date_from` (0 bila tanpa tanggal awal).
 */
openingBalance: number, 
/**
 * Jumlah masuk / keluar dalam rentang tanggal (semua halaman).
 */
totalIn: number, totalOut: number, 
/**
 * Saldo di akhir rentang tanggal.
 */
closingBalance: number, };
