// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StockCardQuery = { productId: number, 
/**
 * Hanya satu batch; saldo dihitung per batch.
 */
batchId: number | null, 
/**
 * `YYYY-MM-DD`, inklusif.
 */
dateFrom: string | null, dateTo: string | null, offset: number, limit: number, };
