// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StockRow = { productId: number, code: string, name: string, genericName: string | null, baseUnitName: string, rackName: string | null, minStockBase: number, 
/**
 * Total stok semua batch (satuan terkecil).
 */
stockBase: number, 
/**
 * Stok yang bisa dijual: batch tidak terkunci dan belum lewat ED.
 */
sellableBase: number, 
/**
 * Stok di batch yang sudah lewat ED.
 */
expiredBase: number, 
/**
 * ED terdekat di antara batch yang masih punya stok.
 */
nearestExpiry: string | null, batchCount: number, 
/**
 * Nilai persediaan (Σ qty × HPP, rupiah). Hanya untuk user dengan VIEW_COST.
 */
stockValue: number | null, };
