// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockFilter } from "./StockFilter";

export type StockListQuery = { 
/**
 * Cari nama, generik, kode, atau barcode persis.
 */
q: string | null, categoryId: number | null, rackId: number | null, filter: StockFilter, offset: number, limit: number, };
