// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupplierInput = { id: number | null, name: string, address: string | null, phone: string | null, npwp: string | null, paymentTermDays: number, isActive: boolean, };
