// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupplierPaymentMethod } from "./SupplierPaymentMethod";

export type SupplierPaymentInput = { purchaseId: number, 
/**
 * `YYYY-MM-DD`.
 */
paymentDate: string, amount: number, method: SupplierPaymentMethod, reference: string | null, note: string | null, };
