// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Supplier = { id: number, 
/**
 * Dibuat otomatis oleh sistem (SUP0001), tidak bisa diubah.
 */
code: string, name: string, address: string | null, phone: string | null, npwp: string | null, 
/**
 * Tempo pembayaran default (hari) untuk faktur kredit.
 */
paymentTermDays: number, isActive: boolean, createdAt: string, createdBy: string | null, };
