// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupplierPaymentMethod } from "./SupplierPaymentMethod";

export type SupplierPaymentRow = { id: number, 
/**
 * Nomor bukti `BH-2609-0001`.
 */
number: string, purchaseId: number, paymentDate: string, amount: number, method: SupplierPaymentMethod, 
/**
 * No. transfer / giro.
 */
reference: string | null, note: string | null, createdAt: string, createdBy: string | null, voidedAt: string | null, voidedBy: string | null, voidReason: string | null, };
