// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupplierDebtRow = { purchaseId: number, number: string, supplierId: number, supplierName: string, invoiceNumber: string, invoiceDate: string, dueDate: string, grandTotal: number, 
/**
 * Pembayaran yang tidak dibatalkan.
 */
paid: number, 
/**
 * Retur ke supplier yang memotong hutang.
 */
returned: number, outstanding: number, 
/**
 * Negatif = lewat jatuh tempo.
 */
daysLeft: number, };
