// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Supplier } from "./Supplier";

export type SupplierPage = { rows: Array<Supplier>, total: number, };
