// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Jumlah nota dan nilainya (rupiah).
 */
export type Tally = { count: number, amount: number, };
