// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Harga di faktur termasuk PPN, belum termasuk PPN, atau tanpa PPN.
 */
export type TaxMode = "INCLUDED" | "EXCLUDED" | "NONE";
