// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pengaturan pajak (FLOW.md §6: PKP ya/tidak; PPN pembelian selalu ditangani).
 */
export type TaxSettings = { 
/**
 * Apotek Pengusaha Kena Pajak: PPN masukan bisa dikreditkan, jadi tidak masuk HPP.
 */
isPkp: boolean, 
/**
 * Tarif PPN default untuk faktur pembelian (basis point, 11% = 1100).
 */
ppnRateBp: number, };
