// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopProduct = { productId: number, name: string, qtyBase: number, baseUnitName: string, amount: number, };
