// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceMode } from "./PriceMode";
import type { PriceTierInput } from "./PriceTierInput";

export type UnitPriceInput = { productUnitId: number, priceMode: PriceMode, 
/**
 * Dipakai bila `MANUAL`; diabaikan bila `AUTO`.
 */
sellPrice: number, 
/**
 * Semua tier aktif satuan ini. Tier lama yang tidak dikirim akan dinonaktifkan.
 */
tiers: Array<PriceTierInput>, };
