// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRow } from "./UserRow";

export type UserListResult = { rows: Array<UserRow>, total: number, };
