// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type UserInput = { id: number | null, username: string, fullName: string, roles: Array<Role>, 
/**
 * Nomor SIPA (apoteker) atau SIPTTK (TTK).
 */
licenseNumber: string | null, 
/**
 * Wajib untuk user baru; kosong saat ubah = tidak diganti.
 */
password: string | null, 
/**
 * Wajib untuk user baru; kosong saat ubah = tidak diganti.
 */
pin: string | null, isActive: boolean, };
