// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * Satu pengguna untuk tabel dan form. Hash password/PIN tidak pernah dikirim ke frontend.
 */
export type UserRow = { id: number, username: string, fullName: string, roles: Array<Role>, 
/**
 * `SIPA` (apoteker) / `SIPTTK` (TTK).
 */
licenseType: string | null, licenseNumber: string | null, hasPin: boolean, isActive: boolean, createdAt: string, 
/**
 * Username pembuat; `None` untuk pemilik dari setup awal.
 */
createdBy: string | null, lastLoginAt: string | null, };
