// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionUser } from "./SessionUser";
import type { UserRow } from "./UserRow";

export type UserSaveResult = { user: UserRow, 
/**
 * Diisi bila yang diubah adalah akun yang sedang login (peran/nama bisa berubah).
 */
session: SessionUser | null, };
