// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type UserListQuery = { 
/**
 * Cari username, nama lengkap, atau nomor SIPA/SIPTTK.
 */
q: string | null, role: Role | null, includeInactive: boolean, offset: number, limit: number, };
